#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
# My Preferences

 # ls="ls --color=auto --group-directories-first --sort=extension" \
alias \
	sudo="doas" \
	YT="straw-viewer" \
	ytg="gtk-straw-viewer" \
	fonts_refresh="fc-cache -f -v" \
	cat="bat -p" \
	ls="exa -lmH --group-directories-first --icons --sort=extension --no-user" \
	uptime="uptime -p; printf 'since: $(uptime -s)\n'" \
	upto="/usr/bin/uptime" \
	lsa="exa -alFgh --group-directories-first" \
	p="doas pacman" \
	r="doas pacman -Rns" \
	u="doas pacman -U" \
	syu="doas pacman -Syu" \
	ss="doas pacman -Ss" \
	pz="pacman -Qi | awk '/^Name/{name=\$3} /^Installed Size/{print \$4\$5, name}' | sort -h" \
	vimwiki="nvim ~/tent/hogwarts/home/vimwiki/index.md" \
	fm600="fm6000 -r -c random -o artix -de=dwm -n" \
	cc="{xclip -sel c -o -r; printf '\n'; } >> ~/.local/share/larbs/snippets" \
	cr=' : > ~/.local/share/larbs/snippets'


# Colorize commands when possible.
alias \
    ip="ip --color=auto" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

alias \
	actconda="conda activate /home/me/pustak/datascience/env" \
	sourceconda="source ~/.config/zsh/conda_zsh_init"


# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	fc="doas firewall-cmd" \
	trem="transmission-remote" \
	sdn="doas shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	em="/usr/bin/emacs -nw" \
  	emacs="emacsclient -c -a 'emacs'" \
	xi="doas xbps-install" \
	xx="find -type f | fzf -m" \
	xr="doas xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
	tldr="cht.sh"

### ARCHIVE EXTRACTION
# usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2|*.tbz2)   tar xjf $1   ;;
      *.tar.gz|*.tgz)    tar xvzf $1   ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.xz)        unxz $1	;;
      *.exe)       cabextract $1 ;;
      *.lzma)      unlzma $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# root privileges
alias doas="doas"

# navigation
alias \
	..='cd ..' \
	...='cd ../..' \
	.3='cd ../../..' \
	.4='cd ../../..' \
	.5='cd ../../../..' \
	.6='cd ../../../../..'

# navigation
up () {
	local d=""
	local limit="$1"

	# Default to limit of 1
	if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
		limit=1
	fi

	for ((i=1;i<=limit;i++)); do
		d="../$d"
	done

	# perform cd. Show error if cd fails
	if ! cd "$d"; then
		echo "couldn't go up $limit dirs.";
	fi
}

# Quicker Navigation
fcd() {
	cd "$(find -type d | fzf -m)"
}

open() {
	xdg-open "$(find -type f | fzf)"
}

alias getpath="find -type f | fzf | tr -d '\n' | xclip -selection c"

# pacman and yay
alias syyu='doas pacman -Syyu'                 # update only standard pkgs
alias pyu="paru -Sua --noconfirm"              # update only AUR pkgs
alias psyu="paru -Syu --noconfirm"              # update standard pkgs and AUR pkgs
alias unlock="doas rm /var/lib/pacman/db.lck"    # remove pacman lock
alias cleanup='doas pacman -Rns $(pacman -Qtdq)' # remove orphaned packages

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

# git
alias \
	addup='git add -u' \
	addall='git add .' \
	branch='git branch' \
	checkout='git checkout' \
	commit='git commit -m' \
	fetch='git fetch' \
	pull='git pull' \
	push='git push' \
	status='git status' \
	tag='git tag' \
	newtag='git tag -a'

# the terminal rickroll
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'

# switch between shells
alias \
	tobash="doas chsh $USER -s /bin/bash && echo 'Now log out.'" \
	tozsh="doas chsh $USER -s /bin/zsh && echo 'Now log out.'" \
	tofish="doas chsh $USER -s /bin/fish && echo 'Now log out.'"

# youtube-dl
alias \
	ytdl="yt-dlp" \
	yta-aac="youtube-dl --extract-audio --audio-format aac " \
	yta-best="youtube-dl --extract-audio --audio-format best " \
	yta-flac="youtube-dl --extract-audio --audio-format flac " \
	yta-m4a="youtube-dl --extract-audio --audio-format m4a " \
	yta-mp3="youtube-dl --extract-audio --audio-format mp3 " \
	yta-opus="youtube-dl --extract-audio --audio-format opus " \
	yta-vorbis="youtube-dl --extract-audio --audio-format vorbis " \
	yta-wav="youtube-dl --extract-audio --audio-format wav " \
	ytv-best="youtube-dl -f bestvideo+bestaudio "
